// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flood-app-api.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckAlertsRequest struct {
	AlertMode            uint64   `protobuf:"varint,1,opt,name=alertMode,proto3" json:"alertMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAlertsRequest) Reset()         { *m = CheckAlertsRequest{} }
func (m *CheckAlertsRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAlertsRequest) ProtoMessage()    {}
func (*CheckAlertsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flood_app_api_2cfe5a1711c362f2, []int{0}
}
func (m *CheckAlertsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAlertsRequest.Unmarshal(m, b)
}
func (m *CheckAlertsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAlertsRequest.Marshal(b, m, deterministic)
}
func (dst *CheckAlertsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAlertsRequest.Merge(dst, src)
}
func (m *CheckAlertsRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAlertsRequest.Size(m)
}
func (m *CheckAlertsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAlertsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAlertsRequest proto.InternalMessageInfo

func (m *CheckAlertsRequest) GetAlertMode() uint64 {
	if m != nil {
		return m.AlertMode
	}
	return 0
}

type CheckAlertsResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAlertsResponse) Reset()         { *m = CheckAlertsResponse{} }
func (m *CheckAlertsResponse) String() string { return proto.CompactTextString(m) }
func (*CheckAlertsResponse) ProtoMessage()    {}
func (*CheckAlertsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flood_app_api_2cfe5a1711c362f2, []int{1}
}
func (m *CheckAlertsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAlertsResponse.Unmarshal(m, b)
}
func (m *CheckAlertsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAlertsResponse.Marshal(b, m, deterministic)
}
func (dst *CheckAlertsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAlertsResponse.Merge(dst, src)
}
func (m *CheckAlertsResponse) XXX_Size() int {
	return xxx_messageInfo_CheckAlertsResponse.Size(m)
}
func (m *CheckAlertsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAlertsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAlertsResponse proto.InternalMessageInfo

func (m *CheckAlertsResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type TestAlertsRequest struct {
	TestMessage          string   `protobuf:"bytes,1,opt,name=testMessage,proto3" json:"testMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestAlertsRequest) Reset()         { *m = TestAlertsRequest{} }
func (m *TestAlertsRequest) String() string { return proto.CompactTextString(m) }
func (*TestAlertsRequest) ProtoMessage()    {}
func (*TestAlertsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flood_app_api_2cfe5a1711c362f2, []int{2}
}
func (m *TestAlertsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAlertsRequest.Unmarshal(m, b)
}
func (m *TestAlertsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAlertsRequest.Marshal(b, m, deterministic)
}
func (dst *TestAlertsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAlertsRequest.Merge(dst, src)
}
func (m *TestAlertsRequest) XXX_Size() int {
	return xxx_messageInfo_TestAlertsRequest.Size(m)
}
func (m *TestAlertsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAlertsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestAlertsRequest proto.InternalMessageInfo

func (m *TestAlertsRequest) GetTestMessage() string {
	if m != nil {
		return m.TestMessage
	}
	return ""
}

type TestAlertsResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestAlertsResponse) Reset()         { *m = TestAlertsResponse{} }
func (m *TestAlertsResponse) String() string { return proto.CompactTextString(m) }
func (*TestAlertsResponse) ProtoMessage()    {}
func (*TestAlertsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flood_app_api_2cfe5a1711c362f2, []int{3}
}
func (m *TestAlertsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAlertsResponse.Unmarshal(m, b)
}
func (m *TestAlertsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAlertsResponse.Marshal(b, m, deterministic)
}
func (dst *TestAlertsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAlertsResponse.Merge(dst, src)
}
func (m *TestAlertsResponse) XXX_Size() int {
	return xxx_messageInfo_TestAlertsResponse.Size(m)
}
func (m *TestAlertsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAlertsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestAlertsResponse proto.InternalMessageInfo

func (m *TestAlertsResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type MuteAlertRequest struct {
	MuteAlertPriority    uint64   `protobuf:"varint,1,opt,name=muteAlertPriority,proto3" json:"muteAlertPriority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MuteAlertRequest) Reset()         { *m = MuteAlertRequest{} }
func (m *MuteAlertRequest) String() string { return proto.CompactTextString(m) }
func (*MuteAlertRequest) ProtoMessage()    {}
func (*MuteAlertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flood_app_api_2cfe5a1711c362f2, []int{4}
}
func (m *MuteAlertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MuteAlertRequest.Unmarshal(m, b)
}
func (m *MuteAlertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MuteAlertRequest.Marshal(b, m, deterministic)
}
func (dst *MuteAlertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MuteAlertRequest.Merge(dst, src)
}
func (m *MuteAlertRequest) XXX_Size() int {
	return xxx_messageInfo_MuteAlertRequest.Size(m)
}
func (m *MuteAlertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MuteAlertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MuteAlertRequest proto.InternalMessageInfo

func (m *MuteAlertRequest) GetMuteAlertPriority() uint64 {
	if m != nil {
		return m.MuteAlertPriority
	}
	return 0
}

type MuteAlertResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MuteAlertResponse) Reset()         { *m = MuteAlertResponse{} }
func (m *MuteAlertResponse) String() string { return proto.CompactTextString(m) }
func (*MuteAlertResponse) ProtoMessage()    {}
func (*MuteAlertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flood_app_api_2cfe5a1711c362f2, []int{5}
}
func (m *MuteAlertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MuteAlertResponse.Unmarshal(m, b)
}
func (m *MuteAlertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MuteAlertResponse.Marshal(b, m, deterministic)
}
func (dst *MuteAlertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MuteAlertResponse.Merge(dst, src)
}
func (m *MuteAlertResponse) XXX_Size() int {
	return xxx_messageInfo_MuteAlertResponse.Size(m)
}
func (m *MuteAlertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MuteAlertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MuteAlertResponse proto.InternalMessageInfo

func (m *MuteAlertResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckAlertsRequest)(nil), "pb.checkAlertsRequest")
	proto.RegisterType((*CheckAlertsResponse)(nil), "pb.checkAlertsResponse")
	proto.RegisterType((*TestAlertsRequest)(nil), "pb.testAlertsRequest")
	proto.RegisterType((*TestAlertsResponse)(nil), "pb.testAlertsResponse")
	proto.RegisterType((*MuteAlertRequest)(nil), "pb.muteAlertRequest")
	proto.RegisterType((*MuteAlertResponse)(nil), "pb.muteAlertResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FloodAlertAppServiceClient is the client API for FloodAlertAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FloodAlertAppServiceClient interface {
	CheckAlerts(ctx context.Context, in *CheckAlertsRequest, opts ...grpc.CallOption) (*CheckAlertsResponse, error)
	TestAlerts(ctx context.Context, in *TestAlertsRequest, opts ...grpc.CallOption) (*TestAlertsResponse, error)
	MuteAlerts(ctx context.Context, in *MuteAlertRequest, opts ...grpc.CallOption) (*MuteAlertResponse, error)
}

type floodAlertAppServiceClient struct {
	cc *grpc.ClientConn
}

func NewFloodAlertAppServiceClient(cc *grpc.ClientConn) FloodAlertAppServiceClient {
	return &floodAlertAppServiceClient{cc}
}

func (c *floodAlertAppServiceClient) CheckAlerts(ctx context.Context, in *CheckAlertsRequest, opts ...grpc.CallOption) (*CheckAlertsResponse, error) {
	out := new(CheckAlertsResponse)
	err := c.cc.Invoke(ctx, "/pb.FloodAlertAppService/checkAlerts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *floodAlertAppServiceClient) TestAlerts(ctx context.Context, in *TestAlertsRequest, opts ...grpc.CallOption) (*TestAlertsResponse, error) {
	out := new(TestAlertsResponse)
	err := c.cc.Invoke(ctx, "/pb.FloodAlertAppService/testAlerts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *floodAlertAppServiceClient) MuteAlerts(ctx context.Context, in *MuteAlertRequest, opts ...grpc.CallOption) (*MuteAlertResponse, error) {
	out := new(MuteAlertResponse)
	err := c.cc.Invoke(ctx, "/pb.FloodAlertAppService/muteAlerts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FloodAlertAppServiceServer is the server API for FloodAlertAppService service.
type FloodAlertAppServiceServer interface {
	CheckAlerts(context.Context, *CheckAlertsRequest) (*CheckAlertsResponse, error)
	TestAlerts(context.Context, *TestAlertsRequest) (*TestAlertsResponse, error)
	MuteAlerts(context.Context, *MuteAlertRequest) (*MuteAlertResponse, error)
}

func RegisterFloodAlertAppServiceServer(s *grpc.Server, srv FloodAlertAppServiceServer) {
	s.RegisterService(&_FloodAlertAppService_serviceDesc, srv)
}

func _FloodAlertAppService_CheckAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloodAlertAppServiceServer).CheckAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FloodAlertAppService/CheckAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloodAlertAppServiceServer).CheckAlerts(ctx, req.(*CheckAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FloodAlertAppService_TestAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloodAlertAppServiceServer).TestAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FloodAlertAppService/TestAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloodAlertAppServiceServer).TestAlerts(ctx, req.(*TestAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FloodAlertAppService_MuteAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloodAlertAppServiceServer).MuteAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FloodAlertAppService/MuteAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloodAlertAppServiceServer).MuteAlerts(ctx, req.(*MuteAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FloodAlertAppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FloodAlertAppService",
	HandlerType: (*FloodAlertAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "checkAlerts",
			Handler:    _FloodAlertAppService_CheckAlerts_Handler,
		},
		{
			MethodName: "testAlerts",
			Handler:    _FloodAlertAppService_TestAlerts_Handler,
		},
		{
			MethodName: "muteAlerts",
			Handler:    _FloodAlertAppService_MuteAlerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flood-app-api.proto",
}

func init() { proto.RegisterFile("flood-app-api.proto", fileDescriptor_flood_app_api_2cfe5a1711c362f2) }

var fileDescriptor_flood_app_api_2cfe5a1711c362f2 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0x48, 0xa1, 0xd3, 0x8b, 0x9d, 0xb6, 0x51, 0x82, 0x87, 0xb2, 0x27, 0xc1, 0x26,
	0x87, 0x8a, 0x27, 0x11, 0xda, 0x8b, 0xb7, 0x82, 0xc4, 0x27, 0x48, 0xd2, 0x51, 0x83, 0xd5, 0x1d,
	0x77, 0x27, 0x82, 0xef, 0xe9, 0x03, 0xc9, 0xc6, 0x34, 0x4d, 0x93, 0x43, 0x8e, 0xf9, 0xf2, 0x7f,
	0xfc, 0xcc, 0xcf, 0xc2, 0xe4, 0x65, 0xa7, 0xf5, 0x36, 0x4c, 0x98, 0xc3, 0x84, 0xf3, 0x88, 0x8d,
	0x16, 0x8d, 0xa7, 0x9c, 0xaa, 0x25, 0x60, 0xf6, 0x46, 0xd9, 0xfb, 0x7a, 0x47, 0x46, 0x6c, 0x4c,
	0x5f, 0x05, 0x59, 0xc1, 0x2b, 0x18, 0x26, 0x0e, 0x6c, 0xf4, 0x96, 0x2e, 0xbd, 0xb9, 0x77, 0x7d,
	0x16, 0x1f, 0x80, 0x0a, 0x61, 0x72, 0xe4, 0x58, 0xd6, 0x9f, 0x96, 0xd0, 0x87, 0x81, 0x2e, 0x84,
	0x0b, 0x29, 0x8d, 0x61, 0x5c, 0x7d, 0xa9, 0x3b, 0x18, 0x0b, 0x59, 0x39, 0x6e, 0x98, 0xc3, 0xc8,
	0xc1, 0x0d, 0x59, 0x9b, 0xbc, 0x52, 0x65, 0x34, 0x91, 0x5a, 0x00, 0x36, 0xb5, 0x9e, 0x92, 0x15,
	0x9c, 0x7f, 0x14, 0x42, 0x65, 0x7a, 0xdf, 0xb1, 0x80, 0x71, 0xcd, 0x9e, 0x4c, 0xae, 0x4d, 0x2e,
	0x3f, 0xd5, 0x35, 0xdd, 0x1f, 0xea, 0xa6, 0x91, 0xee, 0xab, 0x5b, 0xfe, 0x7a, 0x30, 0x7d, 0x74,
	0x93, 0x96, 0xf1, 0x35, 0xf3, 0x33, 0x99, 0xef, 0x3c, 0x23, 0x5c, 0xc1, 0xa8, 0xb1, 0x0d, 0xfa,
	0x11, 0xa7, 0x51, 0x77, 0xe0, 0xe0, 0xa2, 0xc3, 0xff, 0x0b, 0xd5, 0x09, 0x3e, 0x00, 0x1c, 0xee,
	0xc6, 0x99, 0x0b, 0x76, 0xe6, 0x0b, 0xfc, 0x36, 0xae, 0xf5, 0x7b, 0x80, 0xfa, 0x0c, 0x8b, 0x53,
	0x97, 0x6b, 0x0f, 0x13, 0xcc, 0x5a, 0x74, 0x2f, 0xa7, 0x83, 0xf2, 0x61, 0xdc, 0xfe, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x89, 0x69, 0xa6, 0xfa, 0x2f, 0x02, 0x00, 0x00,
}
