---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.floodAlert.name }}
spec:
  type: {{ .Values.floodAlert.service.type }}
  {{- if .Values.floodAlert.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.floodAlert.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.floodAlert.service.clusterIP }}
  clusterIP: {{ .Values.floodAlert.service.clusterIP }}
  {{- end }}
  selector:
    app: {{ .Values.floodAlert.labels.app }}
  ports:
  - name: grpclb
    port: {{ .Values.floodAlert.externalPort }}


   